from .FotoDomaInline import FotoDomaInline
from .FailDomaInline import FailDomaInline
from .VideoDomaInline import VideoDomaInline
from .DomAdmin import DomAdmin
from .NaseleniPunktAdmin import NaseleniPunktAdmin
from .UlizaAdmin import UlizaAdmin
from .OkrugAdmin import OkrugAdmin
from .RayonAdmin import RayonAdmin
from .TipObectaAdmin import TipObectaAdmin
from .SostoyanieDomaAdmin import SostoyanieDomaAdmin