from .UchastnikRabochaiaGruppaInline import UchastnikRabochaiaGruppaInline
from .ResheniePoProektuInline import ResheniePoProektuInline
from .StatusIspolneniaAdmin import StatusIspolneniaAdmin
from .ProektAdmin import ProektAdmin

from .TipResheniaPoProektuAdmin import TipResheniaPoProektuAdmin
from .UchastnikRabochaiaGruppaAdmin import UchastnikRabochaiaGruppaAdmin